apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-config
data:
  APPLICATION_PROFILE: "hml"
  # DYNAMODB_TABLE_NAME, SNS_TOPIC_ARN, SQS_QUEUE_URL são injetados em runtime pelo CI (vêm de SSM)
