apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: execution
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
