apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution
spec:
  replicas: 2
  selector:
    matchLabels:
      app: execution
  template:
    metadata:
      labels:
        app: execution
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      serviceAccountName: execution
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: execution
          image: ghcr.io/ivanzao/auto-repair-shop-execution:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: execution-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
