apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auto-repair-shop-execution
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: auto-repair-shop-execution
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
