application:
  url: http://localhost:8080
  profile: test

server:
  port: 8080

aws:
  region: us-east-1

dynamodb:
  table:
    name: __injected-by-testcontainers__

sns:
  topic:
    arn: __injected-by-testcontainers__

sqs:
  queue:
    url: __injected-by-testcontainers__

reservation:
  ttl:
    days: 7
  job:
    interval:
      seconds: 3600
